# Generated by Django 5.0.2 on 2024-08-17 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_adquisicion', models.DateField()),
                ('origen', models.CharField(choices=[('comprado', 'Comprado'), ('adoptado', 'Adoptado')], max_length=10)),
                ('pasado_adoptado', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('malo', 'Malo'), ('calle', 'De la calle')], max_length=10, null=True)),
                ('tiene_enfermedades', models.BooleanField(default=False)),
                ('enfermedades', models.TextField(blank=True, null=True)),
                ('ultima_visita_veterinario', models.DateField(blank=True, null=True)),
                ('tratamiento_enfermedades', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
